// <auto-generated />
namespace NguyenVanKhai_lab456.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CrateTableCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrateTableCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202006040227438_CrateTableCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
